name: Distribution canary

on:
#  push:
  schedule:
    - cron: '20 13 * * *'
      
jobs:
  pash:
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-24.04

    runs-on: ${{ matrix.os }}

    steps:
      - name: Install PaSh using the up script and run tests
        run: |
          wget https://raw.githubusercontent.com/binpash/pash/main/scripts/up.sh
          sh up.sh
          ## Inspect it if you wish
          export PASH_TOP="$PWD/pash/src/pash"
          export PATH="$PATH:$PWD/pash"
          cd pash
          ./pa.sh -c "echo hi"
          ./evaluation/tests/test_evaluation_scripts.sh
          
