name: Performance
on:
  # Trigger the workflow on push or pull request,
  # but only for the main branch
  push:
    branches:
      - main
    paths: 
        - compiler/**
        - runtime/**
        - evaluation/**
        - annotations/**
jobs:
  pash-ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2 
      - name: Trigger Performance Tests
        run: |
          # build the new docker images
          curl -s "http://ctrl.pash.ndr.md/job=build_docker"
          # fetch the commit hash
          hash=$(git rev-parse --short HEAD | tr -d "\n")
          # construct the url for performance and correctness
          perf="http://ctrl.pash.ndr.md/job=issue&branch=main&benchmark=PERFORMANCE&commit=$hash"
          #cor="http://ctrl.pash.ndr.md/job=issue&branch=main&benchmark=CORRECTNESS&commit=$hash"
          # issue the correctness tests
          #curl -s "$cor"
          # issue the performance tests
          curl -s "$perf"

